### ISSUE TITLE
Enemy castbar 'fade' colour changing

### ISSUE THREAD

**Issue by Rubeek** [kesava-wow/kuinameplates2#294]
I'll try to explain this to the best of my abilities but it's a little odd. 

I have my castbar setup to display non-interruptible casts in orange and interruptible casts in white.

With the latest update that introduces the castbar fade/flash, when a non-interruptible cast (orange) is successfully cast the bar will suddenly switch to white and fade out as white. I'm not sure if this is an intended side effect of the fade animation but it can be very distracting, it can appear as though an interruptible cast got through. It would be very nice if the castbar kept its colour when fading.

Other than that I'm a fan of the effect, the 'interrupted' indicator is very nice.

**Comment by kesava-wow** [comment]
This is intentional, it's to make it easier to differentiate between a cast which succeeded or was interrupted. If uninterruptible casts remained the same colour, that would create a conflict between interrupted casts (including uninterruptible spells, since you can interrupt them via stuns, etc) and successful uninterruptible casts, besides the text. It's more consistent if the castbar is coloured according to whatever matches the ending state of the cast - although yes, the config options don't currently declare that meaning.

Alternatively I can add a third colour for successful casts.

It is sort of supposed to be distracting, or attention-grabbing.

**Comment by kesava-wow** [comment]
Related: https://github.com/kesava-wow/kuinameplates2/commit/c833cf27b9edf0ab58ba16b4990c2eb4489d1572

**Comment by kesava-wow** [comment]
Fixed recently (options to disable the animation entirely and disable the colour changing were added)
