### ISSUE TITLE
Export Profiles Locations on pc?

### ISSUE THREAD

**Issue by blaggletoad** [kesava-wow/kuinameplates2#301]
Hi guys, just curious where you can find your Profile exports? I would like to send it to a friend and I can't figure out how. haha Thanks!

**Comment by kesava-wow** [comment]
There isn't a way built into the addon. But you can manually copy addons' saved variables from the game files. These are in World of Warcraft/WTF/Account/{your-account}/SavedVariables. In this case the file is called Kui_Nameplates_Core.lua.

You can either entirely overwrite the settings by just copying that file and having them paste it into the same place, overwriting it if it already exists, or you can send them a single profile which they can then manually add to the profiles table.

Where a profile that you want to send looks similar to this (with varying settings of course):

```
		["mine"] = {
			["cvar_clamp_top"] = 0.0499999895691872,
			["cvar_name_only"] = true,
			["clickthrough_friend"] = true,
			["cvar_enable"] = true,
			["castbar_shield"] = false,
			["cvar_clamp_bottom"] = 0.0499999895691872,
			["ignore_uiscale"] = true,
		},
```

The other person can open their SavedVariables/Kui_Nameplates_Core.lua file, and add that snippet to the end of that file, just above the two lines which have curly braces in them, so that the end of the file then looks like this:

```
		},
		["mine"] = {
			["cvar_clamp_top"] = 0.0499999895691872,
			["cvar_name_only"] = true,
			["clickthrough_friend"] = true,
			["cvar_enable"] = true,
			["castbar_shield"] = false,
			["cvar_clamp_bottom"] = 0.0499999895691872,
			["ignore_uiscale"] = true,
		},
	},
}
```

You must use a text editor which doesn't add extra formatting, for example, notepad on Windows.

(You can still comment on closed issues)
