### ISSUE TITLE
[Request] A few things i would like to see

### ISSUE THREAD

**Issue by siven80** [kesava-wow/kuinameplates2#311]
I would love an option to scale your targets nameplate size. 

I like the target glow option, but would also love if it could glow the whole border rather than just the center. Saw this option on my brothers pc in Elvui and liked it.

Would love an option to change the horizontal value of the level and health text.

**Comment by kesava-wow** [comment]
Target scaling: see my reply here: https://github.com/kesava-wow/kuinameplates2/issues/339#issuecomment-431181327

glow: this was the behaviour before I updated the textures to better support scaling along with the global scale option - and this way allows me to have two textures rather than eight (one for each corner of the glow). This branch: https://github.com/kesava-wow/kuinameplates2/tree/feature/full-target-glow is a version with the full eight textures. I may or may not merge it at some point.

Vertical offsets for everything is currently in here: https://github.com/kesava-wow/kuinameplates2/issues/287 (it's obscured a bit because this is just my personal list of things to do).
