### ISSUE TITLE
move personal resources

### ISSUE THREAD

**Issue by cahix** [kesava-wow/kuinameplates2#322]
is there anyway to move the personal resources bar ? it is actually covering my character

**Comment by cahix** [comment]
and is there anyway to change the colour of the personal resources health bar ?

**Comment by kesava-wow** [comment]
You can change the colour of the personal health bar with the /knp > health bars > "self" option (right at the bottom), once you uncheck "class colour self."

Moving the PRD requires you to edit some CVars, though we don't have complete freedom over it, since it's always trying to position itself under your feet. We can only move it up or down. This: https://github.com/kesava-wow/kuinameplates2/issues/269 would add those CVars to KNP's UI.

The two CVars are nameplateSelfTopInset and nameplateSelfBottomInset. These are a percentage of the height of the screen, from 0 to 1, so 0.5 is 50%, meaning the middle of the screen. The defaults are .5 and .2 respectively, meaning the PRD is allowed to move within the area that is 50% away from the top of the screen, and 20% away from the bottom.

So, if the PRD is too high up for you, you can force it to move lower by setting nameplateSelfTopInset to a larger number:
`/run SetCVar('nameplateSelfTopInset',0.6)`

Increase the number until it pushes it down enough.

**Comment by ilu33** [comment]
I'm trying to move the bar by using your interface cvars option but it does nothing. At least nothing I can see. Using the command you mentioned with 0.6 (0.9 did not work) helped and I can actually loot now. But it resets upon logout. Your interface allows only up to 0.5 for some reason.
