### ISSUE TITLE
[Feature Request]Change plate color based on buff/debuff/name

### ISSUE THREAD

**Issue by Solor** [kesava-wow/kuinameplates2#351]
hey kesava, cloud you make a custom template that can change plate's color by unit's buff/debuff/name, it would be great helpful 😀

**Comment by wheatbread** [comment]
Hi!  I came here to request the same thing.  I moved to using Plater, then NameplateKai because the ability to have plates be predetermined colors based on npc names/ ids makes such a huge difference in m+.  

However, I really miss Kuinameplates, so I came to ask (now that m+ starts next week) if it might be possible.

I saw the link above.  Noob question: how do I use it with kui (assuming it still works for shadowlands)?  Will it be possible to export/ import npc color filters I set up to share with my friends?

**Comment by kesava-wow** [comment]
It still works, but you have to edit the file directly to change the names or colours. So sharing would just consist of sending the modified file. See the  readme in [the customs repo](https://github.com/kesava-wow/kuinameplates-customs).

I'd suggest checking https://www.curseforge.com/wow/addons/kuinameplates-target-helper instead (it isn't made by me so obviously I can't guarantee its function, etc.)

**Comment by wheatbread** [comment]
Oh, thanks very much!  I'll do that.

**Comment by kesava-wow** [comment]
I've added auras to this script now: https://github.com/kesava-wow/kuinameplates-customs/blob/master/custom.name-and-target-colour.lua
