### ISSUE TITLE
PRESSED "DEFAULT"  > ALL SETTINGS" AND KUI WONT WORK

### ISSUE THREAD

**Issue by RonyHeat** [kesava-wow/kuinameplates2#368]
Was editing KUI for a new desktop when I accidently hit DEFAULTS in the interface menu. After this NONE of the features of the KUI appeared nor can i bring them back. Ive tried reinstalling as well.

**Comment by kesava-wow** [comment]
I can't reproduce this. And I don't actually implement any behaviour relating to the game's reset button, so KNPs stuff should all be the same (although nameplates will be disabled, by default).

If Kui Nameplates isn't visible under the "add-ons" tab in esc > interface, or doesn't open when you run `/knp` in chat, just make sure KNP is enabled. If it is, it should be giving you an error. You might need to enable error display in order to see that, though: `/run SetCVar('scripterrors',1)ReloadUI()`

Does `/knp dump` open a window with copyable text in it? If so, paste that here.

**Comment by kesava-wow** [comment]
Actually. you might just need to check "Always show nameplates" under esc > interface > names.
