### ISSUE TITLE
Buff not stacking

### ISSUE THREAD

**Issue by Nosidda** [kesava-wow/kuinameplates2#378]
A certain buff (hunter move - Barbed Shot) can be stacked to 3, however when it shows above me it creates a new barbed shot buff instead of stacking. Is there any way to get these to stack? The enemy gets it too however it just adds to it's timer, which is fine. I just don't like that it's separated on mine.

I hope this makes sense, please see my pic.

Thanks
![wowscrnshot_012819_143821](https://user-images.githubusercontent.com/47319850/52205104-02a1ee80-28b1-11e9-9a12-73728d23e0e7.jpg)

**Comment by kesava-wow** [comment]
That'll be because Blizzard decided to implement it as three separate spells, for whatever reason, so they'd need to change it (but don't hold your breath). You could blacklist that specific buff with [KSLC](https://www.curseforge.com/wow/addons/kuispelllistconfig), if just not seeing it is preferable.
