### ISSUE TITLE
size of name growing on selection

### ISSUE THREAD

**Issue by brianspenceni** [kesava-wow/kuinameplates2#387]
Hey not sure if this is new but suddenly when i select a friendly or enemy player their nameplate is massively enlarged (like 20% or so more than usual).  I know i can change the size of nameplates in text but i want to control how much selection makes the nameplate grow (or rather, not grow cause its super annoying and covers too many enemy nameplates visually).

Is there some way to do this?

**Comment by kesava-wow** [comment]
Enable the CVars page. `/knp > cvars`

**Comment by kesava-wow** [comment]
Enable the CVars page. `/knp > cvars`


This is the "target scale" cvar which is built into the game. They reset it for 8.1.5, apparently. KNP would disable it by default, but you need to enable the cvars config page because CVars are persistent and character specific - so I 'ask for permission' before modifying them.
