### ISSUE TITLE
No option to disable minimized nameplate?

### ISSUE THREAD

**Issue by zekeflynn** [kesava-wow/kuinameplates2#419]
Why does the proper nameplate only appear on my selected target and I can't find a way to disable the minimized version when the mob is not selected?

![what](https://user-images.githubusercontent.com/33818126/64010948-1503a400-caf1-11e9-9c3a-cfaa901520b0.png)

**Comment by zekeflynn** [comment]
Also I can't disable fade at all on non-selected targets?? How is this lacking such basic functionalities?

**Comment by kesava-wow** [comment]
Good edit. I'm one person, this is a hobby, and the beta wasn't up very consistently.

Uncheck /knp > text > "hide non-tracked names"

This definition of "tracked" doesn't exist in classic, so everything is nameless by default. These options are the same as in the retail client, currently. 

Fade rules aren't working because my frames have to inherit the vanilla behaviour, and on classic, there is no way to disable the built-in fading behaviour. So I'll disable the fade rules page on classic in the future. 

Uncheck
