### ISSUE TITLE
Dont fade hostile casting not working for pvp targets

### ISSUE THREAD

**Issue by cdavidr** [kesava-wow/kuinameplates2#461]
![image](https://user-images.githubusercontent.com/16137278/86531927-8d668e80-be93-11ea-9d50-c868c715db17.png)
Tried these settings, I think it works for pve mobs, but not players

**Comment by kesava-wow** [comment]
Since you have "interruptible" unchecked and "uninterruptible" checked, this setup only prevents fading of enemies who are casting something uninterruptible. There aren't many uninterruptible spells players can cast.

Also if this is on classic, there are fading behaviours built into the game which can't be disabled. On retail, you still need to disable those by checking "Disable fading" under /knp > cvars.

**Comment by cdavidr** [comment]
tyvm
