### ISSUE TITLE
erratic totem nameplate behavior?

### ISSUE THREAD

**Issue by n1ghtsoul** [kesava-wow/kuinameplates2#471]
This issue has been appearing primarily in arenas and it's most noticeable with grounding totem.

I have totem (minion) nameplates disabled in the default blizzard interface options.

Occasionally, I will see shaman totems displayed with full unit nameplates

Other times I will see them displayed with a minor unit nameplate.

And finally in other scenarios I wont see a nameplate for totems at all.

I've had each of these occurrences both when I am in and out of combat with an enemy shaman.  I have no idea what is dictating this behavior.  Is this a default blizzard behavior, or is something in KuiNP driving this?

**Comment by kesava-wow** [comment]
Totems are inconsistent in PVE, too, generally depending on when they were originally implemented. KNP relies on the default nameplates showing in order to then modify them; it doesn't decide whether or not nameplates get rendered. So if a nameplate is or isn't rendering despite your settings, that's a problem in the game. If the _exact same totem_ from the same player (or the same set of talents, traits, or anything else which might modify that totem) or NPC is behaving inconsistently, then, that might be something in KNP.

All that is to say, I'll keep an eye out for totems. Thanks.
