### ISSUE TITLE
after long usage and testing - several Improvements

### ISSUE THREAD

**Issue by Zeucean** [kesava-wow/kuinameplates2#474]
- MOST Important- Auras - should have the option to hide the cooldown text and only to have the cooldown spiral like in original blizzard nameplates.
- having the option to choose different size for the Target Nameplate - messes up with the fact that minors have different shapes - you end up selecting a minor and because the size looks like a major then you believe that you had selected a major - i believe the size of the target as a feature should be removed.
- positioning of texts like the name, level, hp...  should work with anchors and not only with offsets like if i want to put the name of the mob in the center of nameplate i should just select a anchor to "center" 
- different ways to highlight the target should be added not only the glow- or maybe the Glow should be more solid.

**Comment by kesava-wow** [comment]
1. you can get cooldown frames [with this custom](https://github.com/kesava-wow/kuinameplates-customs/blob/master/custom.simple-aura-mods.lua). I'll think about adding them in this update cycle.
2. there'll be an option to disable target size. The alpha release will have unfinished things sometimes (and sometimes it won't have even been tested, because it's built automatically).
3. yep, but that won't be in this update. KNP was really made to be just what I use, with some simple options on top; not to be extensively customisable (unless you do your own coding). But I'm also slowly writing another version of the layout which would be allow for more customisability.
4. that's what target size is for, there are also target "arrows" (which there's a hidden option to change the texture of), and in this update I was going to make the glow slightly brighter and larger by default, and possibly add a way to brighten the health bar of the target in some way.

(you can still reply to closed issues)
