### ISSUE TITLE
Request: ClassicAuraDuriations aura swipe & instance nameplate scale like ThreatPlates

### ISSUE THREAD

**Issue by x33st0rm** [kesava-wow/kuinameplates2#475]
So i love this addon, but two things are bothering me way too much.

One that there's no swipe cooldown in the aura module, leaving me to read text instead of glancing.

And two, the default instance nameplates are awfully big by default, blocking the view and being annoying.
Trying ThreatPlates for the auras which it have, and it has an option for 50% scale for nameplates in instaces only, which is so nice!

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplates-customs/blob/master/custom.simple-aura-mods.lua enables cooldown frames on auras (and as such allows omnicc and such to modify them) but there are rendering issues when nameplates stack up. I need to look into that but I don't personally miss them so it hasn't been a priority.

I think I'd personally just make frames smaller at all times rather than only in instances. You could to some degree automate switching KNP's profiles when you enter/leave instances, or use a button, with the slash commands, e.g. this would switch to a profile called "smaller", if it existed: /knp profile smaller
