### ISSUE TITLE
How to set target frame size?

### ISSUE THREAD

**Issue by tflo** [kesava-wow/kuinameplates2#478]
Apparently since the most recent beta (flying pig) the sliders for target frame size are dimmed. In your release notes I found

> add options showquesticon, frametargetsize (not exposed, both disabled by default)

But I’m pretty sure that with the version before the target frame size sliders were already there and they were adjustable. (Also the quest mob indicators were activated.)

So, how can I set the target frame size now? (And activate the quest mob indicators?)

Thanks in advance, and thanks for the great add-on!

– Tom

**Comment by kesava-wow** [comment]
I disabled them by default for the beta release because I wanted to work on them a bit more. You can modify options that aren't exposed in the interface with the slash commands: `/knp set show_quest_icon true` and `/knp set frame_target_size true`. On 5 Oct 2020 14:11, Tom <notifications@github.com> wrote:

Apparently since the most recent beta (flying pig) the sliders for target frame size are dimmed. In your release notes I found



add options showquesticon, frametargetsize (not exposed, both disabled by default)



But I’m pretty sure that with the version before the target frame size sliders were already there and they were adjustable. (Also the quest mob indicators were activated.)

So, how can I set the target frame size now? (And activate the quest mob indicators?)

Thanks in advance, and thanks for the great add-on!

– Tom

**Comment by tflo** [comment]
Ah, great, thanks for the slash commands.
