### ISSUE TITLE
beta-flying-pig-mechanical-pony not working in Shadowlands Beta

### ISSUE THREAD

**Issue by Paradox4g** [kesava-wow/kuinameplates2#479]
Not sure what's going on with this build but the only working build I've found for Shadowlands Beta is "beta-talking-horse-sprinting-whale" but it randomly encounters double nameplates. Downloaded "beta-flying-pig-mechanical-pony" in hopes of fixing that issue and found that it doesn't work properly. It will randomly highlight targets but that seems to be it. 

Attached I'm targeting an NPC and it skins the target information but nothing else. I've changed no knp settings.

![image](https://user-images.githubusercontent.com/60015834/95683605-fe63c380-0bb1-11eb-8e31-b66025538420.png)

**Comment by kesava-wow** [comment]
In that screenshot, the only "nameplate" is on your target. All the other units have the old in world floating text. Whenever a unit has the old floating text, that means either nameplates for that unit are disabled in the game's interface options, or the game doesn't render nameplates for that type of unit. So that means using another version of KNP won't make any difference.See the options in Esc > Interface > Names, in particular the checkbox for "always show nameplates" (or something to that effect).(also see the FAQ in the curse description)On 11 Oct 2020 17:08, Paradox4g <notifications@github.com> wrote:
Not sure what's going on with this build but the only working build I've found for Shadowlands Beta is "beta-talking-horse-sprinting-whale" but it randomly encounters double nameplates. Downloaded "beta-flying-pig-mechanical-pony" in hopes of fixing that issue and found that it doesn't work properly. It will randomly highlight targets but that seems to be it.
Attached I'm targeting an NPC and it skins the target information but nothing else. I've changed no knp settings.

**Comment by Paradox4g** [comment]
I didn't know you would reply so quickly so all I did was disable Kui. Enable Evlui nameplates. Saw this reply. Disabled Elvui and re-enabled KUI and it was suddenly working. 

I checked ESC>Interface>Names> "Always show nameplates" was already checked. 

I guess we can close this out as a case of user error. Thanks for the quick reply though!
