### ISSUE TITLE
Targeting & Text

### ISSUE THREAD

**Issue by Themaddmax** [kesava-wow/kuinameplates2#486]
i have 2 issues and this is why i stopped updating until the prepatch happened and was forced to.

1.  When i target a mob, the health bar changes size and gets less tall and wider, i just want it the same as when i am not targeting, i summarise that is  "frame_width_target and frame_height_target" ? if so i cant adjust it to what my normal frame sizes are as its higher then 40 on height so not sure if its just alpha still is why i cant if not i am unsure how i turn this option off and if there isn't one could you add one please? thanks

2. i like having name text in my health bars and just cuting off if its a long name instead of sticking outside of the bar example: "mutated grub" would stick outside the box, i would want it to show  like "mutated..."  there was a option for this but didn't work with newer versions so i never updated was called "kui extras" with a "leftie" option not sure if this was a fan extra or not as i haven't been able to find it again now days when i look online, if this could be added as a option it would be gladly appreciated, note: i can attach the extra folder if needed.

**Comment by kesava-wow** [comment]
1. You're on the alpha. I suggest you switch back to release, 2.26.3d. Otherwise, you can type larger numbers than the sliders allow in the little edit boxes underneath them. It can't be disabled at the moment; I use the alpha to guinea-pig things (and also, the alpha is literally just my copy of the addon. So it might be broken sometimes.)

2. https://github.com/kesava-wow/kuinameplates-customs/blob/master/custom.leftie.lua - "Extras" was moved out into customs because it was easier for me. https://github.com/kesava-wow/kuinameplates-customs#how-do-i-use-this. If you're using customs you must be aware that you need to manually keep them up to date (as was also the case with extras).

**Comment by Themaddmax** [comment]
1. thanks, yeah the targeting thing no longer happens as much now.

2. i tried the steps but i cant even get it to show up inside the addon (tried to download the Kui_Nameplates_Custom its self and place it into addons and also editing it with leftie but they both not working

kinda confused as well i got rid of the extras folder too and i still see extras in my list but not customs its something on my end but i don't know why its doing it.
