### ISSUE TITLE
Feature Request: Ability to move class resource to bottom of personal resource display.

### ISSUE THREAD

**Issue by Chark9** [kesava-wow/kuinameplates2#501]
It would be great if we could swap the class resource to the bottom of the PRD, specifically with the skins that KUI provides. I know there is an option to show default class powers which are on the bottom of the display but some of them overlap the PRD (brewmaster monk stagger for example). I like to attach weak aura buff trackers to the top of the PRD so having the resource below is ideal. 

Attached image shows stagger overlapping monk energy bar using the default resource with KUI PRD. 
![WoWScrnShot_111120_180440](https://user-images.githubusercontent.com/74330065/98874854-07fa7880-2449-11eb-9c23-b6c5ea7cfb2e.jpg)

**Comment by kesava-wow** [comment]
Yes. I'm sort of rewriting classpowers in the background. I might possibly add just a vertical offset option in the meantime.

**Comment by kesava-wow** [comment]
The closing commit introduces options you can get a list of with: `/knp find classpowers_y`
You can get the current value of one of those with: `/knp get classpowers_y_personal`
You can change it with: `/knp set classpowers_y_personal 10`

(This commit also moves class powers to the bottom of the personal nameplate by default because.. it makes more sense)

**Comment by Chark9** [comment]
This is great, thank you!
