### ISSUE TITLE
Adjust plate colors for specific mobs

### ISSUE THREAD

**Issue by Erythros** [kesava-wow/kuinameplates2#527]
I was looking at [a video](https://youtu.be/oif-ZSS6KJk?t=72) where the creator recommends setting different colors per dungeon for specific mobs (like priority interrupt, kitting, CC, etc)

As an example, you can see the Skirmisher here has a different color than the Tick because they are more important
![image](https://user-images.githubusercontent.com/2624183/102368589-ae471a00-3fc3-11eb-8e8f-ac2485a6d760.png)

I was wondering if it's possible to do this in KNP? I don't really like other nameplates xD

**Comment by Shephard83** [comment]
Yes, it is possible.

Look at https://github.com/kesava-wow/kuinameplates-customs how to install a custom KNP file and take the "custom.name-and-target-colour.lua" file there to modify the bar color of your stated mobs.

**Comment by Erythros** [comment]
Oh, cool!
Do you know if there's a preset made for Shadowlands dungeons?
I found [this](https://addonswow.com/kuinameplates-target-helper) randomly on Google, but I don't know much about it.

**Comment by Shephard83** [comment]
Sorry, I haven't found any presets yet, but your linked KNP Target Helper sounds nice. Never heard from it, so I will give it a try :)

**Comment by kesava-wow** [comment]
I'd suggest trying [Kui Nameplates Target Helper](https://www.curseforge.com/wow/addons/kuinameplates-target-helper) instead of the custom if you aren't accustomed to editing lua files. Just note it isn't made by me, and I haven't tried it myself.

Either way, I intend to add this to KNP at some point in the future.

(Also the site you found is a scraper which, as well as violating authors' rights by not asking for permission, is probably out of date and might insert other things into the downloads. Look for addons on Curse or WoWI instead.)
