### ISSUE TITLE
Nameplates overlap (incorrectly) when far away but stack correctly when close

### ISSUE THREAD

**Issue by wcardosodev** [kesava-wow/kuinameplates2#549]
When I'm near multiple enemies in melee the nameplates stack (image):
![image](https://user-images.githubusercontent.com/17492466/111042370-fba51d00-8434-11eb-94ff-980001b703f3.png)

However when I'm far away they overlap and I can't see all the nameplates (image): 
![image](https://user-images.githubusercontent.com/17492466/111042312-bed92600-8434-11eb-9763-b1852e93845d.png)

What can i do to fix this?

**Comment by kesava-wow** [comment]
I'm not completely sure but it looks like your nameplates are "clamped" to that position; the game doesn't want to move them any further up, so it just starts overlapping them instead. There are options for clamping in /knp > cvars; you might want to reduce the top clamp distance.The game itself controls nameplate movement. Other than the stacking/overlapping option and a few other cvars (which means "console variable"; they're settings built into the game), add-ons can't move them because they're restricted frames. So if this isn't because they're clamped, there's nothing else you can do. It's something blizzard would need to change.On 13 Mar 2021 19:48, William Cardoso ***@***.***> wrote:
When I'm near multiple enemies in melee the nameplates stack (image):

However when I'm far away they overlap and I can't see all the nameplates (image):

What can i do to fix this?

**Comment by wcardosodev** [comment]
Thank you, I changed the clamped top variable to 0.1 and thats much better thank you!
